#!/bin/bash
#  _               _
# | |__   __ _ ___| |__  _ __ ___
# | '_ \ / _` / __| '_ \| '__/ __|
# | |_) | (_| \__ \ | | | | | (__
# |_.__/ \__,_|___/_| |_|_|  \___|

stty -ixon # Disable ctrl-s and ctrl-q.
shopt -s autocd #Allows you to cd into directory merely by typing the directory name.
HISTSIZE= HISTFILESIZE= # Infinite history.

# Setting Bash prompt. Capitalizes username and host if root user (my root user uses this same config file).
if [ "$EUID" -ne 0 ]
	then export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"
	else export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]ROOT\[$(tput setaf 2)\]@\[$(tput setaf 4)\]$(hostname | awk '{print toupper($0)}') \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"
fi

export GPG_TTY=$(tty)

# no idea gonna comment out unless it breaks
#shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
#vf() { $EDITOR $(fzf) ;}

# aliases in here
source /home/$USER/.bash_aliases

# autogenerated shortcuts
source /home/$USER/.shortcuts.sh

# golang
export GOPATH=/home/$USER/go
export GOBIN=/home/$USER/go/bin

# path
export PATH=$PATH:/home/$USER/go/bin
export CDPATH=$CDPATH:$GOPATH/src
export CDPATH=$CDPATH:$GOPATH/src/github.com/UlisseMini
source /home/$USER/.shortcuts.sh
source /home/peep/.shortcuts.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/peep/google-cloud-sdk/path.bash.inc' ]; then . '/home/peep/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/peep/google-cloud-sdk/completion.bash.inc' ]; then . '/home/peep/google-cloud-sdk/completion.bash.inc'; fi
