#!/bin/bash
if [ "$1" != "" ]; then
    mkdir -p "$1" || exit 1
    cd "$1"       || exit 1
fi

name=${PWD##*/}

makefile=$(cat <<EOF
all: build

build:
	gcc $name.c -o $name

run:
	@gcc $name.c -o $name
	@exec ./$name

# build binaries for a bunch of different systems.
release:
	mkdir -p ./bin
	gcc $name.c -o bin/$name
	x86_64-w64-mingw32-gcc $name.c -o bin/$name
EOF
)

mainfile=$(cat <<-EOF
#include <stdio.h>

int main(int argc, char const* argv[]) {
    puts("Hello, world!");
    return 0;
}

EOF
)

echo "Initializing c project \"$name\""
echo -n "$makefile" > ./Makefile || exit 1
echo "Created Makefile"

echo -n "$mainfile" > ./$name.c  || exit 1
echo "Created $name.c"
