#!/bin/sh

# This script is called by i3 on startup.

# Increase key speed via a rate change
xset r rate 300 50
# Remap caps lock to escape (makes vimcraft much easier!)
setxkbmap -option caps:escape
