#!/bin/sh
# This script ensures that i3 will spawn a calculator.
# If IPython is installed, it will run IPython, otherwise it will run
# Python.
([ -e /usr/bin/ipython ] && ipython --no-confirm-exit --no-banner) || python -q
